### ISSUE TITLE
Replace Gitpod by Github Codespaces

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure-Samples/workshop-migrate-jboss-on-app-service#84]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Gitpod is not mandatory, anyone can run the workshop from its desktop VS Code.
If we provide a Cloud based IDE it would be more relevant to support [Github Codespaces](https://github.com/features/codespaces)

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by JasonFreeberg** [comment]
Thanks for the feedback. We looked into GitHub Codespaces, but it's currently only available through a GitHub Team/Organization (due to current billing limitations as I understand from the GitHub team). So if we wrote the workshop with GitHub Codespaces then participants wouldn't be able to follow the workshop unless they were a part of a GitHub Org/Team.

**Comment by danieloh30** [comment]
To go through the workshop using local VS Code, you need to install CLI tools(maven, jq, az, etc.) and extension(MTA) manually.
